# Hexo Configuration
title: My Hexo Blog
subtitle: 分享我的技術與生活
description: Bycard 的技術文章與教學分享，涵蓋前端、後端與投資分析。
author: Your Name
language: zh-TW
timezone: Asia/Taipei

# URL
url: https://bycard01.github.io/Bycard/
root: /Bycard/      # GitHub Pages 子目錄
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
category_dir: categories
index_dir: ''

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: true
titlecase: false
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: '  '

# Deployment
deploy:
  type: git
  repo: https://github.com/Bycard01/Bycard.git
  branch: gh-pages

# Plugins
plugins:
  - hexo-generator-sitemap
  - hexo-generator-feed
  - hexo-deployer-git
  - hexo-generator-index
  - hexo-generator-category
  - hexo-generator-tag

# Sitemap
sitemap:
  path: sitemap.xml

# Feed
feed:
  type: atom
  path: atom.xml
  limit: 20
